### ISSUE TITLE
VVVV not booting anymore after adding Notuiv to the packs folder. Error when using vpm

### ISSUE THREAD

**Issue by score100** [meso-unimpressed/Notuiv#2]
Hi there, unfortunately VVVV won't boot anymore if I add Notuiv to the /packs folder. It just show's the gray square until forever and nothing happens. VVVV version is vvvv_50beta38.1_x64. Net Framework 4.7 is installed using windows 10 with latest upgrades on an HP Pavilion gaming laptop.

Before adding it there I tried adding it through vpm, but then I get an error when installing md.stdl:
`Installing md.stdl
Compilation error:
(8,9): error CS0246: The type or namespace name 'Newtonsoft' could not be found (are you missing a using directive or an assembly reference?)
(68,19): error CS0103: The name 'JArray' does not exist in the current context`
Vpm uses edge as a browser for some reason (firefox is standard browser). Is that intended and may it be related?

**Comment by microdee** [comment]
that error occures when vpm is unzipped with explorer and windows puts these assemblies in sandboxed mode. unzipping vpm with 7zip solves this. also new version is out which is uploaded in a 7z so you can't use explorer.

I close the issue once dependencies are installed for you via vpm correctly and you don't get this exception anymore.

**Comment by score100** [comment]
Hi, installing via vpm worked that way indeed. Bit strange still that it does not open when just manually adding the pack. Anyway, I have notuiv now working. Thanks!
